---
#lancement des playbook de toutes les instances 
#playbook front "haproxy / nfs server"
- import_playbook: deploy_front.yml
#playbook backends 1 "kitty"
- import_playbook: deploy_backends1.yml
#playbook backends 2 "Docker ifconfig.io" 
- import_playbook: deploy_backends2.yml
#playbook backends 2 "Docker wordpress / nfs client"
- import_playbook: deploy_backends3.yml
