global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats

defaults
    log global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend frontend1
    bind *:80
    default_backend backend1

frontend frontend2
    bind *:81
    default_backend backend2

backend backend1
    balance roundrobin
    http-check send meth GET  uri /health
    option httpchk
    http-check expect status 200
    server 57.128.65.150:8080 check
    server 135.125.15.126:8080 backup


backend backend2
    balance roundrobin
    http-check send meth GET  uri /health
    option httpchk
    http-check expect status 200
    server server1 192.168.2.121 :8080 check
    server server1 192.168.2.162:8081 backup


listen stats
    bind *:8080
    stats enable
    stats hide-version
    stats realm Haproxy\ Statistics
    stats uri /
    stats auth username:password
