---
frontend:
  hosts:
    57.128.81.148:
      ansible_user: debian
      ansible_become: True
backend_1:
  hosts:
    162.19.70.219:
      ansible_user: debian
      ansible_become: True
    51.91.147.171:
      ansible_user: debian
      ansible_become: True
backend_2:
  hosts:
    57.128.87.138:
      ansible_user: debian
      ansible_become: True
    146.59.241.147:
      ansible_user: debian
      ansible_become: True

